/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProRequestsRouteImport } from './routes/pro.requests'
import { Route as ProHistoryRouteImport } from './routes/pro.history'
import { Route as ProExploreRouteImport } from './routes/pro.explore'
import { Route as ProEarningsRouteImport } from './routes/pro.earnings'
import { Route as ProDashboardRouteImport } from './routes/pro.dashboard'
import { Route as PUsernameRouteImport } from './routes/p.$username'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard_.reviews'
import { Route as DashboardProfessionalsRouteImport } from './routes/dashboard_.professionals'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard_.portfolio'
import { Route as DashboardExploreRouteImport } from './routes/dashboard_.explore'
import { Route as DashboardCoinsRouteImport } from './routes/dashboard_.coins'
import { Route as DashboardAiInterviewRouteImport } from './routes/dashboard_.ai-interview'
import { Route as AdminVerifyRouteImport } from './routes/admin.verify'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminCoinsRouteImport } from './routes/admin.coins'
import { Route as ProReviewIdRouteImport } from './routes/pro.review.$id'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProRequestsRoute = ProRequestsRouteImport.update({
  id: '/pro/requests',
  path: '/pro/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProHistoryRoute = ProHistoryRouteImport.update({
  id: '/pro/history',
  path: '/pro/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProExploreRoute = ProExploreRouteImport.update({
  id: '/pro/explore',
  path: '/pro/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ProEarningsRoute = ProEarningsRouteImport.update({
  id: '/pro/earnings',
  path: '/pro/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProDashboardRoute = ProDashboardRouteImport.update({
  id: '/pro/dashboard',
  path: '/pro/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PUsernameRoute = PUsernameRouteImport.update({
  id: '/p/$username',
  path: '/p/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/dashboard_/reviews',
  path: '/dashboard/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfessionalsRoute = DashboardProfessionalsRouteImport.update({
  id: '/dashboard_/professionals',
  path: '/dashboard/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/dashboard_/portfolio',
  path: '/dashboard/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardExploreRoute = DashboardExploreRouteImport.update({
  id: '/dashboard_/explore',
  path: '/dashboard/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoinsRoute = DashboardCoinsRouteImport.update({
  id: '/dashboard_/coins',
  path: '/dashboard/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAiInterviewRoute = DashboardAiInterviewRouteImport.update({
  id: '/dashboard_/ai-interview',
  path: '/dashboard/ai-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifyRoute = AdminVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoinsRoute = AdminCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => AdminRoute,
} as any)
const ProReviewIdRoute = ProReviewIdRouteImport.update({
  id: '/pro/review/$id',
  path: '/pro/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tentang': typeof TentangRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/dashboard/ai-interview': typeof DashboardAiInterviewRoute
  '/dashboard/coins': typeof DashboardCoinsRoute
  '/dashboard/explore': typeof DashboardExploreRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/professionals': typeof DashboardProfessionalsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/p/$username': typeof PUsernameRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/earnings': typeof ProEarningsRoute
  '/pro/explore': typeof ProExploreRoute
  '/pro/history': typeof ProHistoryRoute
  '/pro/requests': typeof ProRequestsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/pro/review/$id': typeof ProReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tentang': typeof TentangRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/dashboard/ai-interview': typeof DashboardAiInterviewRoute
  '/dashboard/coins': typeof DashboardCoinsRoute
  '/dashboard/explore': typeof DashboardExploreRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/professionals': typeof DashboardProfessionalsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/p/$username': typeof PUsernameRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/earnings': typeof ProEarningsRoute
  '/pro/explore': typeof ProExploreRoute
  '/pro/history': typeof ProHistoryRoute
  '/pro/requests': typeof ProRequestsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/pro/review/$id': typeof ProReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/interview': typeof InterviewRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tentang': typeof TentangRoute
  '/admin/coins': typeof AdminCoinsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/dashboard_/ai-interview': typeof DashboardAiInterviewRoute
  '/dashboard_/coins': typeof DashboardCoinsRoute
  '/dashboard_/explore': typeof DashboardExploreRoute
  '/dashboard_/portfolio': typeof DashboardPortfolioRoute
  '/dashboard_/professionals': typeof DashboardProfessionalsRoute
  '/dashboard_/reviews': typeof DashboardReviewsRoute
  '/p/$username': typeof PUsernameRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/earnings': typeof ProEarningsRoute
  '/pro/explore': typeof ProExploreRoute
  '/pro/history': typeof ProHistoryRoute
  '/pro/requests': typeof ProRequestsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/pro/review/$id': typeof ProReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/interview'
    | '/login'
    | '/register'
    | '/tentang'
    | '/admin/coins'
    | '/admin/users'
    | '/admin/verify'
    | '/dashboard/ai-interview'
    | '/dashboard/coins'
    | '/dashboard/explore'
    | '/dashboard/portfolio'
    | '/dashboard/professionals'
    | '/dashboard/reviews'
    | '/p/$username'
    | '/pro/dashboard'
    | '/pro/earnings'
    | '/pro/explore'
    | '/pro/history'
    | '/pro/requests'
    | '/admin/'
    | '/dashboard/'
    | '/pro/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/interview'
    | '/login'
    | '/register'
    | '/tentang'
    | '/admin/coins'
    | '/admin/users'
    | '/admin/verify'
    | '/dashboard/ai-interview'
    | '/dashboard/coins'
    | '/dashboard/explore'
    | '/dashboard/portfolio'
    | '/dashboard/professionals'
    | '/dashboard/reviews'
    | '/p/$username'
    | '/pro/dashboard'
    | '/pro/earnings'
    | '/pro/explore'
    | '/pro/history'
    | '/pro/requests'
    | '/admin'
    | '/dashboard'
    | '/pro/review/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/interview'
    | '/login'
    | '/register'
    | '/tentang'
    | '/admin/coins'
    | '/admin/users'
    | '/admin/verify'
    | '/dashboard_/ai-interview'
    | '/dashboard_/coins'
    | '/dashboard_/explore'
    | '/dashboard_/portfolio'
    | '/dashboard_/professionals'
    | '/dashboard_/reviews'
    | '/p/$username'
    | '/pro/dashboard'
    | '/pro/earnings'
    | '/pro/explore'
    | '/pro/history'
    | '/pro/requests'
    | '/admin/'
    | '/dashboard/'
    | '/pro/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InterviewRoute: typeof InterviewRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TentangRoute: typeof TentangRoute
  DashboardAiInterviewRoute: typeof DashboardAiInterviewRoute
  DashboardCoinsRoute: typeof DashboardCoinsRoute
  DashboardExploreRoute: typeof DashboardExploreRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardProfessionalsRoute: typeof DashboardProfessionalsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  PUsernameRoute: typeof PUsernameRoute
  ProDashboardRoute: typeof ProDashboardRoute
  ProEarningsRoute: typeof ProEarningsRoute
  ProExploreRoute: typeof ProExploreRoute
  ProHistoryRoute: typeof ProHistoryRoute
  ProRequestsRoute: typeof ProRequestsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ProReviewIdRoute: typeof ProReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pro/requests': {
      id: '/pro/requests'
      path: '/pro/requests'
      fullPath: '/pro/requests'
      preLoaderRoute: typeof ProRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/history': {
      id: '/pro/history'
      path: '/pro/history'
      fullPath: '/pro/history'
      preLoaderRoute: typeof ProHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/explore': {
      id: '/pro/explore'
      path: '/pro/explore'
      fullPath: '/pro/explore'
      preLoaderRoute: typeof ProExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/earnings': {
      id: '/pro/earnings'
      path: '/pro/earnings'
      fullPath: '/pro/earnings'
      preLoaderRoute: typeof ProEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/dashboard': {
      id: '/pro/dashboard'
      path: '/pro/dashboard'
      fullPath: '/pro/dashboard'
      preLoaderRoute: typeof ProDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$username': {
      id: '/p/$username'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof PUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/reviews': {
      id: '/dashboard_/reviews'
      path: '/dashboard/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/professionals': {
      id: '/dashboard_/professionals'
      path: '/dashboard/professionals'
      fullPath: '/dashboard/professionals'
      preLoaderRoute: typeof DashboardProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/portfolio': {
      id: '/dashboard_/portfolio'
      path: '/dashboard/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/explore': {
      id: '/dashboard_/explore'
      path: '/dashboard/explore'
      fullPath: '/dashboard/explore'
      preLoaderRoute: typeof DashboardExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/coins': {
      id: '/dashboard_/coins'
      path: '/dashboard/coins'
      fullPath: '/dashboard/coins'
      preLoaderRoute: typeof DashboardCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/ai-interview': {
      id: '/dashboard_/ai-interview'
      path: '/dashboard/ai-interview'
      fullPath: '/dashboard/ai-interview'
      preLoaderRoute: typeof DashboardAiInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verify': {
      id: '/admin/verify'
      path: '/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AdminVerifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coins': {
      id: '/admin/coins'
      path: '/coins'
      fullPath: '/admin/coins'
      preLoaderRoute: typeof AdminCoinsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pro/review/$id': {
      id: '/pro/review/$id'
      path: '/pro/review/$id'
      fullPath: '/pro/review/$id'
      preLoaderRoute: typeof ProReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCoinsRoute: typeof AdminCoinsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerifyRoute: typeof AdminVerifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoinsRoute: AdminCoinsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerifyRoute: AdminVerifyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InterviewRoute: InterviewRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TentangRoute: TentangRoute,
  DashboardAiInterviewRoute: DashboardAiInterviewRoute,
  DashboardCoinsRoute: DashboardCoinsRoute,
  DashboardExploreRoute: DashboardExploreRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardProfessionalsRoute: DashboardProfessionalsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  PUsernameRoute: PUsernameRoute,
  ProDashboardRoute: ProDashboardRoute,
  ProEarningsRoute: ProEarningsRoute,
  ProExploreRoute: ProExploreRoute,
  ProHistoryRoute: ProHistoryRoute,
  ProRequestsRoute: ProRequestsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ProReviewIdRoute: ProReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
